// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xiwnpbwbbxvsqnehfbja.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhpd25wYndiYnh2c3FuZWhmYmphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2NjQwNjEsImV4cCI6MjA1OTI0MDA2MX0.hgOiiygslItaUVTUk56PrRNyQiBty4_4rdXmddvrG3Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);